sudo: required
services:
  - docker

before_install:
  - docker build -t lolero/docker-excercise-section-8-fib-calculator -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lolero/docker-excercise-section-8-fib-calculator yarn run test

after_success:
  - docker build -t lolero/docker-excercise-section-8-fib-calculator-client ./client
  - docker build -t lolero/docker-excercise-section-8-fib-calculator-nginx ./nginx
  - docker build -t lolero/docker-excercise-section-8-fib-calculator-server ./server
  - docker build -t lolero/docker-excercise-section-8-fib-calculator-worker ./worker
#  Log in to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push lolero/docker-excercise-section-8-fib-calculator-client
  - docker push lolero/docker-excercise-section-8-fib-calculator-nginx
  - docker push lolero/docker-excercise-section-8-fib-calculator-server
  - docker push lolero/docker-excercise-section-8-fib-calculator-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-excercise-section-8-fib-calculator"
#  env: "DockerExcerciseSection8FibCalculator-env"
#  bucket_name: "elasticbeanstalk-us-east-2-801047117175"
#  bucket_path: "docker-excercise-section-8-fib-calculator"
#  on:
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"